# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LicensePlateRecognition(object):
    def setupUi(self, LicensePlateRecognition):
        LicensePlateRecognition.setObjectName("LicensePlateRecognition")
        LicensePlateRecognition.resize(857, 554)
        self.centralwidget = QtWidgets.QWidget(LicensePlateRecognition)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 541, 551))
        self.groupBox.setObjectName("groupBox")
        self.lblOriginImage = QtWidgets.QLabel(self.groupBox)
        self.lblOriginImage.setGeometry(QtCore.QRect(10, 19, 531, 461))
        self.lblOriginImage.setText("")
        self.lblOriginImage.setObjectName("lblOriginImage")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(190, 490, 161, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 0, 301, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblLicensePlate = QtWidgets.QLabel(self.groupBox_2)
        self.lblLicensePlate.setGeometry(QtCore.QRect(0, 20, 251, 171))
        self.lblLicensePlate.setText("")
        self.lblLicensePlate.setObjectName("lblLicensePlate")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(550, 200, 301, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lblCharacterZone = QtWidgets.QLabel(self.groupBox_3)
        self.lblCharacterZone.setGeometry(QtCore.QRect(0, 20, 251, 171))
        self.lblCharacterZone.setText("")
        self.lblCharacterZone.setObjectName("lblCharacterZone")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(540, 400, 311, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtLicensePlateCode = QtWidgets.QTextEdit(self.groupBox_4)
        self.txtLicensePlateCode.setEnabled(True)
        self.txtLicensePlateCode.setGeometry(QtCore.QRect(10, 20, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtLicensePlateCode.setFont(font)
        self.txtLicensePlateCode.setObjectName("txtLicensePlateCode")
        LicensePlateRecognition.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LicensePlateRecognition)
        self.statusbar.setObjectName("statusbar")
        LicensePlateRecognition.setStatusBar(self.statusbar)

        self.retranslateUi(LicensePlateRecognition)
        QtCore.QMetaObject.connectSlotsByName(LicensePlateRecognition)

    def retranslateUi(self, LicensePlateRecognition):
        _translate = QtCore.QCoreApplication.translate
        LicensePlateRecognition.setWindowTitle(_translate("LicensePlateRecognition", "MainWindow"))
        self.groupBox.setTitle(_translate("LicensePlateRecognition", "Ảnh gốc"))
        self.pushButton.setText(_translate("LicensePlateRecognition", "Chọn ảnh có biển số xe máy"))
        self.groupBox_2.setTitle(_translate("LicensePlateRecognition", "Vùng biển số xe đã phát hiện"))
        self.groupBox_3.setTitle(_translate("LicensePlateRecognition", "Tách vùng kí tự của biển số xe"))
        self.groupBox_4.setTitle(_translate("LicensePlateRecognition", "Mã biển số xe"))
        self.txtLicensePlateCode.setHtml(_translate("LicensePlateRecognition", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
